name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v6
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar tests
        run: npm test
